- aim/aim_manager.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/7349fa0a2ad8_epg.py
- aim/db/model_base.py
- aim/db/models.py
- aim/tests/unit/test_aim_manager.py
DB-model for endpoint-groups is missing contracts.
Changes to ACI-converter are also missing.
> Define resources for subnet, VRF, endpoint-groups

- aim/db/migration/alembic_migrations/versions/40855b7eb958_create_bridgedomain_table.py
- aim/db/migration/alembic_migrations/versions/7349fa0a2ad8_epg.py
- aim/db/model_base.py
- aim/db/models.py
- aim/tests/base.py
- aim/tests/unit/test_aim_manager.py
Have used an auto-increment column on the EPG table
to generate an internal ID that will be referenced
by the contracts table. This is needed for resources
that have non-scalar attributes (e.g. list of contracts).
Having an internal ID avoids having primary
keys that use many columns in the table that contains
the non-scalar values. Have updated other ACI model
classes with this internal-ID.
> Add DB model for EPG contracts

- aim/agent/aid/universes/aim_universe.py
- aim/aim_manager.py
- aim/db/migration/alembic_migrations/versions/faade1155a0a_status_model.py
- aim/db/status_model.py
- aim/tests/unit/test_aim_manager.py
closes noironetworks/support#232
> Use external_id as the primary key for Fault objects

- aim/db/models.py
- aim/tests/unit/test_aim_manager.py
Updating ordinary attributes of an EPG was clearing
out all contract provided/consumed relationships
of the EPG because the resource-to-model conversion
function was eagerly resetting contracts.
Closes noironetworks/support#235
> Fix unwanted contract-relationship deletion

- aim/api/status.py
- aim/tests/unit/test_aim_manager.py
Fault severity was recently changed from integer
to a string, but its use in is_error() was not
updated.
> Fix AciStatus.is_error()

- aim/aim_manager.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/74f15b6aee51_endpoint.py
- aim/db/models.py
- aim/exceptions.py
- aim/tests/unit/test_aim_manager.py
Adding a simple resource object for endpoints
which mainly stores endpoint association to EPG.
Also added a utility function from_dn() to
construct an AIM resource from a DN string.
> AIM resource for endpoints

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/converter.py
- aim/agent/aid/universes/aci/tenant.py
- aim/tests/base.py
- aim/tests/etc/aim.conf.test
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_structured_hash_tree.py
- aim/tools/cli/debug/hashtree.py
For the most part these rules are pretty straight-forward
except for handling of in/out filters in subjects. The
AIM-to-ACI converter translates these to pseudo ACI MOs like
vzRsFiltAtt__In/vzRsFiltAtt__Out, but the hash-tree nodes
have the correct ACI MOs (vzSubj -> vzInTerm -> vzRsFiltAtt,
vzSubj -> vzOutTerm -> vzRsFiltAtt).
A few small changes were needed to ACI universe code to
handle the use-cases presented by vzInTerm/vzOutTerm.
> Add converter rules for contracts

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
Faults reported for subject-to-filter relations
were either ignored completely or raising exceptions
in AID. This change fixes fault reporting for
such cases where the fault parent in ambiguous by
using newly added utility methods in apicapi
DNManager.
> Fixes for faults reported for filter relations

- aim/agent/aid/universes/aci/converter.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/aim_manager.py
- aim/config.py
- aim/tests/base.py
- aim/tests/etc/aim.conf.test
- aim/tests/etc/aim.conf.test.2
- aim/tests/etc/aim.conf.test.empty
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tools/cli/debug/manager.py
- etc/aim/aim.conf
- requirements.txt
When events are received from the WS interface on a particular
APIC object, we need to retrieve all the interesting related
items in order to properly build the hash tree.
More specifically, when a RS gets modified from an APIC object,
the latter should be completely retrieved together with all its
references.
> Retrieve children from events

- aim/agent/aid/universes/aci/tenant.py
- aim/api/status.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
A recent patch was assuming the "dn" property to exists in every AIM resource. Add such property to AciFaults as well (that can retrieve its value by their external identifier).
> Add DN property to AciFault objects

- aim/agent/aid/event_handler.py
- aim/agent/aid/event_services/README.rst
- aim/agent/aid/event_services/event_service_base.py
- aim/agent/aid/event_services/polling.py
- aim/agent/aid/event_services/rpc.py
- aim/agent/aid/event_services/rpc_service.py
- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/tenant.py
- aim/common/utils.py
- aim/config.py
- aim/db/tree_model.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/agent/event_services/base.py
- aim/tests/unit/agent/event_services/test_polling.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/agent/test_event_handler.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tests/unit/tools/cli/test_db_config.py
- aim/tools/cli/debug/event_service_polling.py
- aim/tools/cli/debug/event_service_rpc.py
- etc/aim/aim.conf
- requirements.txt
- setup.cfg
In order to improve AID performance, we are getting rid of the
current polling mechanism in favor of a more modular and event
driven approach. The main AID service will listen on a configurable
unix domain socket, waiting for datagrams coming from external
services that will issue the following events:
- serve: modify the current tenant list and reconcile state. An
event_service can issue this command when a tenant is added/removed
in AIM;
- reconcile: reconcile current tenants' state.
More than one event_service can run at the same time, and even
different combinations for each AID process (although unadvised).
In this patch, the following event_services are implemented:
- polling service: Keeps today's functionality by polling the DB
every few seconds. We should always run this service …
> Event driven AID

- aim/agent/aid/universes/aci/converter.py
- aim/aim_manager.py
- aim/api/infra.py
- aim/api/resource.py
- aim/db/infra_model.py
- aim/db/migration/alembic_migrations/versions/d8abdb89ba66_hostlink.py
- aim/db/models.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
Host connections to switch-ports can now be
managed as AIM resource. Also EndpointGroups
can now be statically bound to switch-ports.
> Add support for host-links

- aim/api/resource.py
- aim/tests/unit/agent/test_agent.py
- aim/tools/cli/debug/hashtree.py
"hashtree reset" command is added for debug purposes, a tenant
can be specified in order to affect a single tenant's hash tree.
> Add a debug command for tree reset purposes

- aim/aim_manager.py
- aim/api/status.py
- aim/db/hashtree_db_listener.py
- aim/db/migration/alembic_migrations/versions/faade1155a0a_status_model.py
- aim/db/status_model.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_hashtree_db_listener.py
- When sync status goes to FAILED, propagate to all the children
recursively;
- When sync status goes to PENDING, propagate to parent (unless already
synced) and children recursively (no object can be created without
its parent anyways);
- When a new object is created in a subtree, apply the above.
> Propagate object status to the proper relatives

- aim/aim_manager.py
- aim/db/migration/alembic_migrations/versions/3ef7607a41b0_contracts.py
- aim/db/migration/alembic_migrations/versions/40855b7eb958_create_bridgedomain_table.py
- aim/db/migration/alembic_migrations/versions/7349fa0a2ad8_epg.py
- aim/db/migration/alembic_migrations/versions/8e313fbeb93b_l3out.py
- aim/db/models.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tests/unit/tools/cli/test_manager.py
New semantics:
- Tenant object must always exist in order for children to be
created;
- Tenant object now supports faults;
- When deleting an AIM object, the AIM manager will try to delete
its whole monitored subtree.
> Set tenant as a foreign key for AIM resources

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
Monitor threads run by acitoolkit and react whenever they critically
fail.
> Monitor web socket threads

- aim/agent/aid/universes/aci/aci_universe.py
- aim/config.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
Whenever we see a websocket critical thread die, rotate the
list of APIC IP addresses and retry WS connection. Eventually
dies after running out of IPs.
> Use thread monitors to rotate between APIC hosts

- aim/agent/aid/event_services/rpc.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/base_universe.py
- aim/db/tree_model.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/test_hashtree_db_listener.py
Sometimes, multiple events can reach the same AIM tenant regarding
the same set of objects. In these cases, multiple subsequent failures
are possible and can lead to a premature setting of the error state
for an AIM object. In order to mitigate this problem, the following
actions are taken:
- Squash similar events in the ACI tenant manager to avoid creating
too many duplicates in APIC;
- Add a failure cooldown period in which a specific item can keep
failing without increasing the number of tentatives before impacting
its sync state.
The root cause of this problem, to be addressed by a subsequent patch,
is that notification events are sent by the AIM manager before the
DB transaction actually commits! So we end up sending multiple
"reconcile" events within a single transaction, and AID …
> Better handling of fast events

- aim/api/resource.py
- aim/common/hashtree/structured_tree.py
- aim/db/hashtree_db_listener.py
- aim/db/tree_model.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tests/unit/test_structured_hash_tree.py
Today, every time ad AIM object gets in SYNC_FAILED state, we
remove the corresponding entry from the proper hashtree. This can
sometimes cause unexpected datapath loss due to the subsequent
deletion of the object itself from APIC.
For example, an ACI VRF would face deletion from APIC just because
an update to its display name set an invalid value! To avoid
such issue, this patch puts the hashtree node in a new state called
"error" instead of deleting it from the tree. When a node is in error
state, it will be excluded from the hashtree difference calculation
without stopping the procedure, so that its subtree can be checked
for inconsistencies.
TODO: error nodes still participate the hash calculation, making the
diff operation more inefficient when such nodes are present.
> Avoid deleting objects when in error state

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/aim_lib/db/model.py
- aim/aim_lib/nat_strategy.py
- aim/exceptions.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
* Pre-exisiting L3Outside now keeps using whatever VRF is set, and the newly created NAT BD uses this VRF.
* For no-NAT strategy, when create_l3outside is called, pre-existing L3Outside becomes an owned object so that its vrf_name can be later modified. It goes back to being pre-existing on delete_l3outside.
* For no-NAT strategy, when ExternalNetwork is connected to a VRF, the old value of L3Outside's vrf_name is saved and then restored when the VRF is disconnected from the ExternalNetwork.
Closes noironetworks/support#429
> Changes to NAT VRF handling in NAT library

- aim/agent/aid/universes/aci/error.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/base_universe.py
- aim/agent/aid/universes/errors.py
- aim/config.py
- aim/tests/unit/agent/aid_universes/test_aci_error.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/test_agent.py
We define a few error categories, each of which has a different
impact on the universe handling it:
- OPERATION_CRITICAL: the operation will never succeed (eg. malformed
object), universe will put the corresponding item in error state;
- OPERATION_TRANSIENT: the operation might eventually succeed and it's
failing for temporary reasons (eg. object parent doesn't exist
during creation), universe will retry until configured tentatives;
- SYSTEM_TRANSIENT: the system is currently broken regardless of the
operation, but might recover eventually (eg. network partition),
this category is currently ignored;
- SYSTEM_CRITICAL: the whole system is broken and cannot be recovered
regardless of the operation (eg. wrong APIC certificate or
credentials), the universe will terminate the AID process.
> Introduce error categories for better exception handling

- aim/db/migration/alembic_migrations/versions/1249face3348_domains.py
- aim/db/models.py
There are some cases of pre-existing EPGs that have either physical
or virtual domains linked that don't exist in AIM.
Because AIM doesn't monitor infra objects yet, this could cause
a FK reference exception and the monitored object won't be created
properly.
Closes noironetworks/support#435
> Remove FK constraint from EPG's domains

- aim/agent/aid/universes/aci/tenant.py
- aim/aim_manager.py
- aim/common/hashtree/structured_tree.py
- aim/db/hashtree_db_listener.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_hashtree_db_listener.py
In certain cases, like external networks, we need to add some RS
items, like provided/consumed contracts, in a monitored object.
Achieve this by not setting monitored objects in pending state
if updates other than the monitored flag itself happen.
Also, share some of the relevant tree building code between AIM and
AID.
> Allow owned RS objects within a monitored resource

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/aim_manager.py
- aim/api/status.py
- aim/db/hashtree_db_listener.py
- aim/tests/base.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tree_manager.py
- Empty sync_status doesn't exist anymore, sync_pending will be
the default;
- Observer thread in K8S will now also build the hashtree. Errors
in building the hashtree will result in status reset instead of
information loss;
- Move TreeBuilder in the tree_manager module, since it's not DB
specific;
> Improve status management and K8S watcher reliability

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
To avoid websocket subscription errors on older version of ACI,
test all the managed object classes to see whether they are
supported.
> Ensure ACI cross version compatibility

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- requirements.txt
Occasionally, APIC lose track of an open web-socket and is unable
to open subscriptions for any new URLs, returning a 405 error.
In these cases, we should reconnect the web-socket for all the
tenants in AID.
If this fix appears to be insufficient to recover from such
cases, we should consider killing AID after a certain number
of failures.
Fixes noironetworks/support 499
> Reconnect Web-Socket on ACI error 405

- aim/aim_store.py
- aim/common/utils.py
- aim/db/hashtree_db_listener.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tools/cli/commands/db_migration.py
- aim/tools/cli/debug/hashtree.py
- aim/tree_manager.py
Use of FakeContext in hash-tree listener was
causing inadvertent modification of the DB
session associated with a store. This fix
avoids that modification and also cleans up
HashTreeDbListener a bit.
Closes noironetworks/support#505
> Fix session modification in DB-listener

- aim/agent/aid/universes/aci/aci_universe.py
- aim/aim_manager.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/test_agent.py
For optimization purposes, we don't fire DB calls to update a status
that is not changing compared to the previous version. For managed
objects transitioning to monitored however this could be critical,
as the Hashtree builder expects a status update in order to remove
the nodes from all the trees.
> Force sync status change for monitored objects

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/converters/utils.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/aim_manager.py
- aim/api/resource.py
- aim/api/status.py
- aim/common/hashtree/base.py
- aim/common/hashtree/structured_tree.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tests/unit/test_structured_hash_tree.py
- aim/tree_manager.py
As AIM becomes a schema instead of a library, let AID manage
completely status objects and their state, so that we don't
need to rely on northbound orchestration systems to do so.
This change reaches this goal with the following:
- AIM now doesn't set any Status object for newly created/updated
objects;
- Status default sync_state is now N/A (covers aimctl get calls);
- On hashtree differences, AID sets the SYNC_PENDING state;
- SYNC_PENDING objects are represented by a new metadata called
"pending" in the hashtree;
- Hashtree nodes that are converged, but with the "pending"
attribute set, are put in SYNCED state by AID;
- SYNC_ERROR continues to work as before.
NOTE: Monitor state update can now be unreliable when multiple AIDs
are running. Will be addressed by future commits
> Manage object status asynchronously

- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/aim_store.py
- aim/k8s/api_v1.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_k8s_watcher.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
Thirdparty Aci objects in Kubernetes always use a
configured namespace in Kubernetes. This restriction
is removed for native Kubernetes objects. Native
objects from all namespaces are now watched and synced
by K8s-watcher/AID.
The agent in test_agent are needed to avoid comparing
tenant-trees unrelated to the test code (these are seen
when running with a Kubernetes store).
Also filter out k8s Pod objects if they use host-networking
(i.e. non-ACI).
> Support operations on multiple Kubernetes namespaces

- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/aim_manager.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_k8s_watcher.py
Fault objects will be automatically cleaned up by the operational
universe.
> Cleanup status objects whenever the parent is deleted

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/k8s/k8s_watcher.py
when observe_and_monitor_loop runs, it only exits the function when
an error occurs or the thread is stopped. This because it's blocked
in a loop internal to the one already provided by the decorator.
Because of that, whenever an error occurs its retry count is increased
by the decorator without ever having a chance to be reset. This
change makes sure that the only loop in this method is the
decorator itself.
In addition, save hashtrees from the K8S watcher every time for
operational resources, even if they look like empty update, so
that we don't lose information about the node error state.
> Reset k8s watcher retries number after a clean monitoring iteration

- aim/agent/aid/universes/aci/converter.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/5d975a5c2d60_vmm_injected_objects.py
- aim/db/models.py
- aim/k8s/api_v1.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
* Move replica-set under namespace, make deployment
name a regular attribute and add guid
* Rename VmmInjectedGroup to VmmInjectedContGroup
for consistency with ACI name. Add reference to
ReplicaSet.
> AIM resource updates to VMM injected objects

- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/aim_manager.py
- aim/tests/unit/agent/aid_universes/test_k8s_watcher.py
- aim/tools/cli/commands/manager.py
Processing AciStatus events for Pods that are meant to
be hidden messes up the config hash-tree by inserting
unwanted nodes. To avoid this two fixes are added:
Fix 1: Avoid creating unwanted AciStatus object in
get_status() for DELETED events.
Fix 2: All AciStatus events for a hidden Pod are
treated as DELETED events.
> Fixes to filtering of certains Pods in Kubernetes watcher

- aim/agent/aid/universes/aci/tenant.py
Whenever a topology/ object needs to be retrieved, do a get for
both itself and its subtree, as APIC won't return the object itself
during a subtree get.
> Get root object on ACI topology model

- aim/agent/aid/universes/aci/converter.py
- aim/agent/aid/universes/aci/tenant.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/5d975a5c2d60_vmm_injected_objects.py
- aim/db/models.py
- aim/tests/etc/aim.conf.test
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_structured_hash_tree.py
VmmInjected objects have now moved to the compUni
tree. Also vmmInjectedCont objects are now
implicitly created by APIC, so we don't create them
during conversion anymore.
> Adapt to injected object changes on APIC

- aim/api/infra.py
- aim/api/resource.py
- aim/db/hashtree_db_listener.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tree_manager.py
Hashtree reset doesn't work for single tenant requests, which is
really critical if we ever need to run this command on a system in
production without affecting all the users.
> Fix hashtree reset

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/tree.py
- aim/common/hashtree/structured_tree.py
- aim/common/utils.py
- aim/db/api.py
- aim/db/hashtree_db_listener.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/migration/alembic_migrations/versions/accaff4a0907_action_log.py
- aim/db/status_model.py
- aim/db/tree_model.py
- aim/k8s/api_v1.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tree_manager.py
Allow northbound orchestration systems using SQL store to build an action log instead of directly modifying the hashtrees, so to reduce the points of contention in the database. 
Closes issue noironetworks/support #554
> Non blocking tree creation

- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aim_universe.py
Whenever an AIM object switches its monitored state, the object
is moved from the Monitored tree (current state) to the Config tree
(desired state). Doing this causes the following:
1) Configuration universe created the TAG on ACI for the object;
2) Monitored universe tries to re-create the object in AIM with
monitored = True: this fails by design;
3) Events arrive for #1, and on the ACI universe, the object is
now in the Config tree (current state) so on the next AID
iteration #2 doesn't happen anymore. Everything is synced.
If #2 happens before #1 however, then the object is put in Error
state, preventing #2 from happening (the AIM monitored state of the
object is still False. So the affected tree will be the Config
even though this happened in the Monitored Universe!). This causes …
> Don't put objects in error state while changing monitored value

- aim/agent/aid/universes/aci/converter.py
- aim/aim_lib/nat_strategy.py
- aim/api/resource.py
- aim/common/utils.py
- aim/db/models.py
- aim/tests/etc/aim.conf.test
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/tools/cli/test_manager.py
- aim/tools/cli/commands/manager.py
Two new attributes are added to the EPG resource:
- vmm_domains: list of dictionaries describing VMMs to which the
EPG refers to;
- physical_domains: list of dictionaries describing physdoms to
which the EPG refers to.
right now, only name and type (in the case of VMM) can be specified.
In future, we can add extra attributes to custom VMM capabilities.
the old attributes 'physical_domain_names' and 'openstack_vmm_names'
are still around and can be used both for reading and writing
new references, but their value will be mirrored in the vmm_domains
and physical_domains attributes.
> Add support for multiple VMM types

- aim/db/infra_model.py
- aim/tests/unit/test_infra_manager.py
They are needed now once we start to allow different
interface_name and pod_id.
> Also return interface_name and pod_id in get_switch_and_port_for_host()

- aim/agent/aid/universes/aci/converter.py
- aim/config.py
- aim/tests/unit/agent/aid_universes/test_converter.py
Some situations, such as older switch hardware, require us to have
the ability to disable configuration of Micro-Segmentation support
on the VMM domain associations with EPGs. This patch adds that
configuration option, which removes this attribute from APIC
configuration when associating VMM Domains with EPGs.
> Add config option to disable micro-segmentation

- aim/aim_lib/nat_strategy.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
The "Limit IP Learning to subnets" flag on external BDs is currently
set to the default of False. This should be set to True in order to
avoid loss of connectivity.
> Change IP learning on external BDs

- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/migration/alembic_migrations/versions/dd2f91cf1b1e_set_nat_bd_ip_learn.py
Commit fc9ee7b1794986c18e8a024b0b9c4653f82709da changed the
defualt value for the "Limit IP learning to subnets" flag. A
migration is needed to update existing data in the table.
> Update External BD entries

- aim/agent/aid/universes/aim_universe.py
- aim/tests/unit/agent/test_agent.py
Today, the monitored universe skips the deletion of root objects
with a warning message that can often be confused with actual divergence.
On top of that, the action cache logs all these deletion attempts as
if they were part of an unfixable divergence. We should skip the
deletion at a previous time in the reconciliation cycle, so that
AID still doesn't "smile" (after all, we are monitoring a
non-existent object) but so that we don't cause divergence either.
> Properly skipp root deletion for monitored objects

- aim/agent/aid/universes/aci/converter.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/6d55c6f80f40_svi.py
- aim/db/models.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
1. This was introduced in the last patch while addressing the review comment
to change the naming of those tables. Apparently pep8 UT won't be able to
catch this kind of errors.
2. Also add the rtrIdLoopBack attribute to the model. This is due to the fact
that starting in APIC Euphrates image, it doesn't allow "use router Id as the
loopback addr" checkbox to be checked for the same node but under a different
l3out.
> Fix the foreign key error while running the migration script.

- aim/agent/aid/universes/aci/aci_universe.py
When resetting the ACI tenants, sometimes the thread could be hanging
and scheduling a tree reset woulnd't be enough. Kill the tenant thread
and garbage collect the tenant handler instead, so that AID can
re-provision it on the next iteration and hopefully be able to
properly sync.
> Improve tenant recovery mechanism

- aim/agent/aid/universes/aci/converter.py
- aim/tests/unit/agent/aid_universes/test_converter.py
This will happen while doing ACI to AIM conversion for the secondary
IPs of an SVI for a VPC setup.
> Also handle the case when l3extIp__Member comes.

- aim/aim_lib/nat_strategy.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
The current create_l3outside API doesn't allow the user to pass
empty lists for the physical_domains and vmm_domains parameters.
In order to support workflows where external/NAT EPGs are created
without any initial domain association, empty lists must be
supported.
> Allow no domains for External EPG

- aim/agent/aid/service.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/aim_store.py
- aim/common/hashtree/exceptions.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
- aim/tests/unit/agent/test_agent.py
- aim/tree_manager.py
The previous algorithm for tenant removal was proved to be unreliable
in situations of high load, where there are lots of threads and race
conditions are likely. This would often cause leftover objects laying
around, since the monitored universe would keep syncing in the background
without causing the removal to cease.
With the new algorithm, we have a two phase decision that is taken
before and after the reconciliation cycle. Furthermore, we make sure
that the monitored universes delete all the AIM monitored objects
when they agree on tenant removal. We do so by pretending that the
desired state is empty. Only when a tenant's AIM state is completely
empty (all trees with no root) we finally cleanup the state.
DB transactionality and update lock should ensure this happens
reliably.
> Change tenant removal algorithm.

- aim/api/infra.py
- aim/tests/unit/tools/cli/test_manager.py
- aim/tools/cli/commands/manager.py
The load-mappings command is added, so that the information
specified in the configuration file can be used to create
entries in the HostDomainMappingV2 table. This patch also
adds a call to this command in the load-domains command,
so that the mappings can be created when the domains first
get loaded.
> Add load-mappings command

- aim/agent/aid/service.py
- aim/aim_lib/nat_strategy.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/resource.py
- aim/api/service_graph.py
- aim/db/agent_model.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
With the introduction of the object versioning, only
update/overwrite objects when there are actual changes to avoid
unwanted stale data errors.
> Update DB objects when actually needed.

- aim/common/utils.py
- aim/tools/cli/commands/db_migration.py
In some cases, hashtree reset might fail with a retriable exception.
We should retry such cases to avoid failing the installation.
> Retry hashtree reset during DB upgrade

- aim/agent/aid/universes/aci/converters/service_graph.py
- aim/agent/aid/universes/aci/converters/utils.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/agent/test_agent.py
Do not return empty tDn objects when the AIM value is not set.
> Prevent extra objects from being created in ACI

- aim/db/hashtree_db_listener.py
- aim/db/migration/alembic_migrations/versions/444afa12da26_modify_aim_id_column.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/model_base.py
- aim/db/status_model.py
- aim/tests/unit/test_aim_manager.py
- aim/tree_manager.py
Looks like sqlalchemy re-uses incremental IDs whenever objects are
deleted from the DB. This, together with the fact that there are
cases in which status objects leak without a parent, can cause the
system to go in a non recoverable state where the Status object
of a new AIM resource clashes with a zombie status of the same type.
Although zombie status periodic cleanup needs to be addressed, this
patch only concerns about avoiding the status clash from happeing.
> Change AIM ID column from increment to UUID

- aim/db/migration/alembic_migrations/versions/1b58ffa871bb_add_host_column.py
- aim/db/migration/alembic_migrations/versions/fabed2911290_modify_host_column_size.py
- aim/db/models.py
- aim/db/service_graph_model.py
Some engines have a limit for index keys of 767 characters.
Resize host columns accordingly.
> Modify host column size

- aim/db/model_base.py
- aim/db/tree_model.py
- aim/tests/unit/test_aim_manager.py
We typically don't care about deletion errors: if we try to delete
something that has already been deleted, then the final state is
already what we desire.
However, sqlalchemy rises exceptions whenever a race condition occurs
while trying to delete a DB object. By setting confirm_deleted_rows
to False in the mapping args, we prevent this exception from happening,
thus avoiding one set of possible retriable errors.
> Set confirm_deleted_rows to False

- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/common/utils.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
- aim/tests/unit/agent/test_agent.py
Context should be re-generated at each reconciliation cycle, and
passed down to all universes on a per-operation basis instead of
having each universe instancing their own context.
This will guarantee that the context will be re-generated upon
error.
> Refactor AIM context usage in AID

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
1. For ACI universe, if the parent object was already deleted in the
desired config tree then we don't even put the children deletion into
the queue.
2. Use the DN Manager to compose the parent DN instead. This is the
standard way instead of searching for the next '/'.
> Reduce the children delete requests to APIC

- aim/tests/unit/tools/cli/test_manager.py
The 7.0 package broke the UTs by splitting the CLI ouptut
from a single variable (output_bytes) into stdout and stderr.
This patch adds a method that supports both old and new versions
in the UTs.
> Support new Click CLI package

- requirements.txt
This is a temporary workaround for an issue introduced by version 9.0 of oslo.messaging. A real fix would be to avoid using deprecated API.
> Cap oslo.messaging below version 9.0

- aim/agent/aid/universes/aci/tenant.py
- aim/config.py
Websocket subscription timeouts are configurable in APIC releases
starting with 4.x. This patch adds the ability for the user to
configure the timeout value in AID, which can help with installs
that have a large amount of configured state.
> [WIP] Configurable websocket subscription timeouts

- aim/agent/aid/universes/aci/aci_universe.py
Username/password credentials shouldn't be printed to log files.
> Remove credentials from log message

- aim/db/migration/alembic_migrations/versions/bcdef2211410_status_add_dn.py
This is tracked in https://github.com/noironetworks/support/issues/799.
The DB migration can fail, leaving this DB migration in a half-committed
state, and therefore not idempotent. This adds everything to a single
transaction, ensuring that it can be re-run if it fails.
> Make status DN DB migration atomic

- aim/db/migration/data_migration/status_add_dn.py
The data migration code for the status DN would cause problems
if it tried to migrate information in a status object for a
tenant that no longer exists in AIM DB. Silently ignore these
cases.
> Fix data migration

- aim/db/migration/alembic_migrations/versions/07113feba145_l3out_clones.py
- aim/db/migration/alembic_migrations/versions/2b48bf7f19cb_fix_host_column.py
- aim/db/migration/alembic_migrations/versions/2c47aab91fff_add_dest_name.py
- aim/db/migration/alembic_migrations/versions/308d91b3dadf_security_group_rule_icmp_code.py
- aim/db/migration/alembic_migrations/versions/32e5974ada25_add_epoch_column.py
- aim/db/migration/alembic_migrations/versions/5d975a5c2d60_vmm_injected_objects.py
- aim/db/migration/alembic_migrations/versions/72fa5bce100b_tree_model.py
- aim/db/migration/alembic_migrations/versions/7838968744ce_opflexdevice.py
- aim/db/migration/alembic_migrations/versions/8e313fbeb93b_l3out.py
- aim/db/migration/alembic_migrations/versions/aaabb1155303_aim_faults_nullable_status_id.py
- aim/db/migration/alembic_migrations/versions/aabce110030f_status_add_tenant.py
- aim/db/migration/alembic_migrations/versions/ab9b4e196100_config_model.py
- aim/db/migration/alembic_migrations/versions/abf7bb5a4100_security_groups.py
- aim/db/migration/alembic_migrations/versions/accaff4a0907_action_log.py
- aim/db/migration/alembic_migrations/versions/accfe645090a_agent_resource.py
- aim/db/migration/alembic_migrations/versions/aceb1ac13668_vmm_policy.py
- aim/db/migration/alembic_migrations/versions/babbefa38870_conn_track.py
- aim/db/migration/alembic_migrations/versions/dc598e78e318_service_graph.py
- aim/db/migration/alembic_migrations/versions/faade1155a0a_status_model.py
- aim/db/migration/alembic_migrations/versions/fabed2911290_modify_host_column_size.py
The "Revises" and "Revision ID" entries were incorrect in many
of the migrations. This patch fixes them.
> Fix DB migrations

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/common/hashtree/structured_tree.py
- aim/tests/unit/test_structured_hash_tree.py
Make sure aci_universe has populated the tenant in its tree before
aim_universe can go ahead to remove it. This is to prevent a situation
especially during tempest tests that a tenant is being created and
deleted rapidly. What happens there is that before the tenant thread
can pick up the tenant creation event from APIC then update the
aci_universe tree accordingly, that tenant is already deleted in AIM.
Then the sanity test in aim_universe finalize_deletion_candidates()
will still pass because at that point, both aim and aci universe don't
have that tenant in its tree.
> Don't delete the tenant prematurely

- aim/aim_store.py
- aim/tests/unit/test_aim_manager.py
Add a check to return back an empty list if no aim resources
are provided to get corresponding status objects.
> Fix query_statuses to return empty list if no aim res provided

- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/base_universe.py
Commit caf2d39df23707ca20cb547e0aa1f6b3c596e added a lock for
error handling, which was modified later to its current state
by commit 6256a9b3d3ac96fe0e4f8f12d32a0374c7c52ca5. The only
context manipulating this data structure is the main AID loop,
so locking shouldn't be needed.
Similarly, commit c0ccb3f1900ddb1d519da07783e4ec5f87f01e27 added
locking for calls to observe. Since the main AID loop is the
only context doing this, locking should not be needed.
This patch removes both of the above locks.
There are also cases where the same lock is obtained twice
in the same context. Commit c0ccb3f1900ddb1d519da07783e4ec5f87f01e27
added locking when getting the configured, operational, and monitored
hash trees from the AciTenantManager objects. However, these calls are
only ever made from the …
> Remove Observer and Sync Log Locking

- aim/tests/unit/test_cherrypy_server.py
Skip this UT class as it fails quite often now without even
showing us where it fails exactly. Also this aim-http-server
is not even enabled in our deployment so nobody is really
using it.
> Disable this UT class

- aim/tests/unit/test_aim_manager.py
The UT framework supports checking against a set of default
values when a resource in AIM is created using just the
identity fields. Commit 983d5e677949454f3880049e4587f3c49bd53349
broke this feature, so this patch re-introduces it.
> Fix UT defaults

- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/tenant.py
- aim/config.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/test_agent.py
Starting F, APIC introduced the concept of annotation, designed
to let orchestrators declare ownership over managed objects.
The APIC team wants us to use annotation instead of tags because
the latter impact performance greately, both in terms of memory
and CPU cycle (a task is generated for every new tag).
This patch want to keep compatibility with APIC back and forth,
so we first test APIC for annotation support and then start using
it for ownership, falling back to tags if support is missing.
On upgrade, I expect AIM to just suddenly forget about the
existing tags and push annotations around. This might require an
external script to get rid of the hanging tags.
> Use annotation instead of Tags for ownership

- aim/api/tree.py
- aim/db/hashtree_db_listener.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_hashtree_db_listener.py
We still need to make sure those skipped action logs
got deleted at the end though. This patch will improve
the action logs process time considerably especially
for those SG rules with huge remote_ips list.
> Skip those duplicate SG rules

- aim/db/hashtree_db_listener.py
When action logs are backed up, aim-aid logging should indicate
how many action logs are being processed. This commit adds a log
message at the INFO level if the number of action log messages to
be processed for a given tenant goes above 1,000.
> Add debug to action log processing

- aim/agent/aid/universes/aci/converter.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/4caed435b0cd_add_netflow.py
- aim/db/models.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/tools/cli/test_manager.py
- Code to enable netflow functionality on opnestack setups.
- Added code to establish relationship to vmm domain.
- Tested on live fabric to make sure policies are pushed to leaf and compute nodes.
> Code to enable netflow functionality in openstack setups

- aim/db/migration/alembic_migrations/versions/794ad00f3080_qos_policies.py
Commit 4ce65eda8f4779c840d1a213654151c774930c80 added support for
QoS features in ACI. The DB migrations included foreign key constriants
to other tables, which aren't needed for most AIM ORM objects, since
AIM allows child objects to be configured in the DB before their parent
(except in cases where the child ORM object isn't represented as an AIM
resource, such as SecurityGroupRuleRemoteIp). Changing DB migration
scripts is permitted, provided it happens before a release is created
that includes the DB migraiton.
> Fix AIM QoS DB

- debian/install
The new packaging scripts weren't including the aim.conf file in
the right place. This patch ensures that it gets installed.
> Add aim-aid init script

- aim/agent/aid/universes/aci/aci_universe.py
- aim/config.py
Make the sleep timeout for websocket logins configurable. This may
be needed for installations using cert-based logins.
> Add configurable websocket login monitor timeout

- requirements.txt
The group-based-policy project requires a higher version of
oslo.messaging. Specify requirements that are in line with
what's used upstream.
> Fix requirements for upstream consumers

- aim/tests/etc/aim.conf.test
- requirements.txt
Some upstream consumers require pbr newer than 2.0.
> Fix pbr for upstream consumers

- test-requirements.txt
The mysql package 1.0 no longer supports python2.7. As a result,
use an older version only for UTs (upstream distros will still
support mysql 1.0 with python2.7).
> Avoid mysql 1.0 for py27

- aim/agent/aid/universes/aci/aci_universe.py
When using certificate-based authentication with APIC, APIC doesn't
require periodic logins to refresh authentication, as authentication
is instead managed by certificates. Password-based authentication uses
a periodic login thread in acitoolkit to maintain valid authentication
session with APIC. However, acitoolkit doesn't spawn a login thread if
certificate-based authentication is used. The AIM/AID code currently
checks to make sure that there is always a login thread present, and
if there isn't, it restarts AIM/AID. This patch fixes AIM/AID to only
check the login thread if username/password-based authentication is
used.
> Fix cert-based authentication

- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/migration/alembic_migrations/versions/ffbe2f21aa75_netflow_Rs_string.py
- aim/db/models.py
- aim/tests/unit/test_aim_manager.py
The hash tree comparison fails due to integer types being converted to string values when creating the APIC-side hash tree. These string values result in different hashes in the hash tree for those resources, and therefore AID never reaches sync. This patch converts the integer values used by Netflow Rs object to strings.
Signed-off-by: Tanya Tukade tanyatukade.123@gmail.com
> Fix Netflow reconciliation

- test-requirements.txt
Upstream changes require pinning of packages in order to pass
Travis CI.
> Fix dependencies

- test-requirements.txt
The py36 UTs were failing Travis CI, due to an issue with arguments
in the newer version of python-click. This pins python-click to the
older version. At some point, we'll need a fix for the issue with the
arguments.
> Fix python36 Unit Tests

- debian/control
Commit 4da3a22417ea6f15ac823f8e3abf7275269bb2ab removed the
"python-" prefix from the python-apicapi dependency, which is
incorrect. This reverts that chnage.
> Fix debian packaging

- debian/build-deb.sh
The apicapi dependency was incorrect for python3 (was specified
as pytnon3-python3-apicapi).
> Fix apicapi dependency

- aim/aim_store.py
- test-requirements.txt
The use of the now-removed with_lockmode parameter is meaningless,
since most deployments use a distributed database (e.g. Galera)
that doesn't support distributed locking.
Commit 462b1ea711c91b06bd5e8c5cfcd3e8c3a1d480e5 pinned SQLAlchemy
in order to avoid the exception that was thrown due to the fact that
the "with_lockmode" parameter was removed from newer versions.
This patch un-pins SQLAlchemy and removes the use of with_lockmode.
> Remove use of with_lockmode

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
If there are failures when we 'serve' the tenants in different universes, some orphaned tenant manager objects can exist. To avoid this situation, we restart the process on failure
> Restart if tenant manager objects are orphaned

- aim/agent/aid/universes/aci/converter.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_converter.py
Set 'convert_monitored' flag to False for Security Group objects
so that they don't show up in the Hash Trees for AIM.
> Set 'convert_monitored' flag to False for Security Group objects

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/config.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
AIM uses the websocket refresh subscription mechanism implemented
in acitoolkit. However, it uses a hard-coded refresh interval (30
seconds), with all subscriptions refreshed at the same time. This
results in bursts of subscription refreshes, and causes excessive
load on the APIC controller when there is a large number of
roots/tenants. The subscription refresh API in acitoolkit was
extended to support passing in URLs for refresh, which allows each
AciTenantManager object to handle their own refreshes.
This patch also ensures that the refresh interval isn't set to
lower than the default for APIC (60 seconds).
> Fix websocket subscription refreshes

- aim/agent/aid/universes/aci/converter.py
- aim/tests/unit/agent/aid_universes/test_converter.py
Different versions of ACI represent the values for the 'ssh' port
in the fromPort and toPort properties differently. A new converter
is added to support the different representations in ACI.
> Support 'ssh' in security group rule converter

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/test_agent.py
The previous code would exit if there were any errors, and
also didn't support cert-based authentication, which doesn't
require a login.
> Fix login manager

- aim/agent/aid/universes/aci/converter.py
- aim/tests/unit/agent/aid_universes/test_converter.py
Support the value 'ssh' for port for properties sFromPort,
sToPort, dFromPort, dToPort used in filter entry by adding
these properties to port_with_ssh converter.
Change-Id: I2bd19c8a6febb83f80cd9f1c932198e0782d0ff4
> Support 'ssh' in filter entry converter

- test-requirements.txt
The release of voluptuous 0.13.0 results in the following
exception during package dependency resolution:
File "./voluptuous/validators.py", line 7, in <module>
from enum import Enum
ImportError: No module named enum
This patch avoids that released version.
> Fix voluptuous

- aim/agent/aid/universes/aci/tenant.py
When APIC is unreachable, serializeation/deserialization errors
can cause exceptions during unsubscribes. This patch catches
those cases.
> Fix unsubscribe exceptions

- aim/db/models.py
The resource update isn't needed when to_attr is called without a session.
> Fix ExternalNetwork session usage

- aim/db/migration/alembic_migrations/versions/7b8a71bee019_ext_net_contracts.py
- aim/db/models.py
Previous patches broke the external network resource CRUD APIs.
For example, creating a new resource was failing to correctly
check for existing contracts. This patch fixes those bugs.
> Fix external network resource APIs

- test-requirements.txt
There were compatibility issues between newer versions of OpenSSL for py37. Pin SSL for py37 until we can figure out the issue.
> Fix for py37

- test-requirements.txt
A new version of greenlet caused the Travis CI gate to fail, due to it trying to rebuild the greenlet library. Pin the version of greenlet for now.
> Fix Travis CI gate

- aim/aim_lib/nat_strategy.py
Commit 9076bd8738e27052e75ec53052e509c54c4b91ea changed the aim_lib semantics to use explicit provided and consumed contract references as top-level resources. However, it missed the code that updates the NAT contract whenever the external network resource is deleted. This patch fixes that case.
> Clean up NAT contracts

- aim/tools/cli/commands/infra.py
Some installations require a system ID length longer than the maximum of 16 characters. Allow this value to be set via configuration files.
> Allow configuration of system ID length

- aim/tools/cli/groups/aimcli.py
The apic_system_id_length option was referenced in commit e123105961b8244581c23d2cc19c7ff9bd43e534, but was never defined. This patch adds the definition.
> Add missing configuration option

- aim/tools/cli/commands/infra.py
Using a positional instead of the named kwargs results in passing incorrect values when creating the manager. This patch switches to use the named kwarg.
> Fix passing paramete to aimctl

- aim/aim_lib/nat_strategy.py
Commit 251a877 removed some code from aim_lib. This patch restores the missing code.
> Replace aim_lib code

- aim/common/utils.py
- aim/tests/etc/aim.conf.test
- aim/tests/unit/tools/cli/test_manager.py
Creating this policy is unnecessary & causes a universe difference between AIM and ACI.
> Removed VMware Policy Creation

- debian/build-deb.sh
- debian/control
- debian/rules
Python2 is EOL, so remove support for it in debian builds.
> Remove python2 support for debian

- aim/agent/aid/universes/aci/tenant.py
- aim/config.py
This patch adds a config knob for enabling/disabling faults while subscribing to the tenants.
> Adding new config to enable/disable faults in tenant subscriptions

- rpm/aci-integration-module.spec.in
Packages for python3 should be prefaced with "python3-".
> Fix python3 build

- rpm/aci-integration-module.spec.in
For python3, we need a python3- prefixed version of acitoolkit.
> Fix acitoolkit requirement

- aim/db/migration/data_migration/static_paths_v2.py
Fix bug where the static path resource comes
as non monitored when it should be monitored.
(cherry picked from commit 28c69ba50e436a2a64f376b8dcec1445479837ee)
> Fix bug in static paths fix

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
For python3.9, the threading.Thread isAlive method was replaced with the is_alive method.
(cherry picked from commit 41669f05eb0d809f2538a8916e77361563e58a0b)
> Fix isAlive

- aim/agent/aid/universes/aci/converter.py
In Openstack a security group rule is configured with Remote IP 0.0.0.0/32, which has an intent to disable all communication towards port that it's assigned to. AIM component of ACI Neutron plugin takes this security group rule and pushes it to APIC as hostprotRemoteIp Policy.
When the policy is programmed in APIC, it's automatically converted to 0.0.0.0 remote IP (the mast /32 is deleted).
At this point AIM would never converge for the corresponding project, since it sees that different remote IP is programmed in APIC (0.0.0.0 vs 0.0.0.0/32) and it tried to correct it by deleting 0.0.0.0 and configuring again 0.0.0.0/32 at the same run.
> Fix for AIM config not converging for hostProtRemoteIP 0.0.0.0/32 [CSCwp32570]
