- .travis.yml
> Enable Travis CI checks

- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/converter.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/api/resource.py
- aim/common/hashtree/structured_tree.py
- aim/db/agent_model.py
- aim/db/hashtree_db_listener.py
- aim/db/migration/alembic_migrations/versions/72fa5bce100b_tree_model.py
- aim/db/tree_model.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tests/unit/test_structured_hash_tree.py
- aim/tools/cli/debug/aid.py
- aim/tools/cli/debug/manager.py
- aim/tools/cli/groups/aimcli.py
- requirements.txt
- test-requirements.txt
Put together all the pieces for end to end AID integration
> Agent end-to-end integration

- aim/agent/aid/universes/aci/converter.py
- aim/db/tree_model.py
- aim/tests/unit/agent/aid_universes/test_converter.py
> Add converter rules for EPG contract relationship

- aim/aim_manager.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/3ef7607a41b0_contracts.py
- aim/db/migration/alembic_migrations/versions/7349fa0a2ad8_epg.py
- aim/db/models.py
- aim/tests/unit/test_aim_manager.py
> Add resource and DB model for contracts/filters

- aim/common/hashtree/structured_tree.py
- aim/db/tree_model.py
- aim/tests/unit/test_structured_hash_tree.py
When updating a node in the hash-tree,
AimHashTreeMaker deletes the subtree at that node
to remove child nodes that are directly
related (e.g. relation-nodes). But this ends
up deleting other unrelated child nodes as
well (those that correspond to other AIM
resources). This problem is fixed by adding
a metadata flag to all child-nodes that are
related to a node, and it is only these
related nodes that are removed during an
update.
> Avoid deleting hash subtree during update

- aim/tests/unit/test_utils.py
- aim/utils.py
> Utility to sanitize display names

- aim/agent/aid/universes/aci/converter.py
- aim/tests/unit/agent/aid_universes/test_converter.py
> Convert vzEntry attributes to support protocol literals

- aim/agent/aid/universes/aci/converter.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/7349fa0a2ad8_epg.py
- aim/db/models.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
> Add flag to disallow traffic between endpoints within an EPG

- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/tenant.py
- aim/api/resource.py
- aim/common/utils.py
- aim/config.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_utils.py
- exponential backoff on tenant thread failure;
- guard for unsupported objects coming from websocket;
- harakiri function for critical errors.
> stability cleanup

- aim/agent/aid/event_services/event_service_base.py
- aim/agent/aid/event_services/polling.py
- aim/agent/aid/event_services/rpc.py
- aim/agent/aid/event_services/rpc_service.py
- aim/agent/aid/service.py
- aim/agent/aid/universes/aci/aci_universe.py
- aim/config.py
- aim/tests/base.py
- aim/tests/etc/aim.conf.test
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_config.py
- aim/tests/unit/tools/cli/test_db_config.py
- aim/tests/unit/tools/cli/test_manager.py
- aim/tools/cli/commands/config.py
- aim/tools/cli/groups/aimcli.py
- etc/aim/aim.conf
- etc/aim/aimctl.conf
Remove dependency from that config everywhere else
> Only use apic_system_id config option in the infra CLI script

- aim/tests/base.py
- aim/tools/cli/commands/infra.py
- aim/tools/cli/groups/aimcli.py
- rpm/aci-integration-module.spec.in
- setup.cfg
* Include sample aimctl.conf in package
* Fix infra CLI to create vpc dict properly
* Register apic_system_id in CLI, and remove it
from test code
Closes noironetworks/support#404
Closes noironetworks/support#405
> Fixes for CLI

- aim/tests/unit/tools/cli/test_shell.py
- aim/tools/cli/commands/db_migration.py
- aim/tools/cli/debug/hashtree.py
> Always create a monitored common tenant

- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/test_agent.py
Mock post_body_dict in apicapi instead of post_body to make the
attributes order irrelevant
> Fix push_aim_resources UT

- aim/aim_lib/nat_strategy.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
> Implement no-NAT strategy

- aim/agent/aid/event_handler.py
- aim/tests/unit/agent/test_event_handler.py
Closes noironetworks/neutron#3
> Create parent directories of Unix socket for events

- aim/agent/aid/universes/aci/converter.py
- aim/aim_manager.py
- aim/api/infra.py
- aim/api/resource.py
- aim/api/schema.py
- aim/api/status.py
- aim/api/types.py
- aim/common/utils.py
- aim/tests/unit/test_aim_manager.py
- aim/tools/cli/commands/manager.py
- requirements.txt
> Generate JSON schema from AIM model

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/config.py
- aim/db/api.py
Also, elevate some useful traceback logs to 'error' level
> Set expire on commit True by default for AID DB sessions

- aim/agent/aid/universes/aci/converter.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_structured_hash_tree.py
> Create service-graph relations from contract only when required

- aim/agent/aid/service.py
- aim/tests/unit/agent/test_agent.py
Sharing the session can lead to transactional
conflicts.
> Don't share DB-session among threads started by AID

- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/tests/unit/agent/aid_universes/test_k8s_watcher.py
Apparently bool() on a GreenThread evaluates to
a False if the GreenThread is not running. This
prevented detection of dead green-threads.
> Fix bug in detection of dead K8s observer threads

- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/k8s/api_v1.py
Also, increase K8S API connection pool size
> Optimize AIM universe get_resources_for_delete

- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/tests/unit/agent/aid_universes/test_k8s_watcher.py
If after processing a Kubernetes event the hash-trees
remain unchanged, then we will skip saving the
trees and notifying the universes about changes.
> Better handling of no-change events in k8s_watcher

- aim/tools/cli/commands/manager.py
Closes noironetworks/support#532
> Make VMM/Physical domains created from CLI as monitored

- aim/agent/aid/universes/aci/tenant.py
> Fixes to handle objects in comp/ tree

- aim/aim_manager.py
- aim/aim_store.py
- aim/config.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/migration/alembic_migrations/versions/baccabeffa81_remove_fks.py
- aim/db/models.py
- aim/db/service_graph_model.py
- aim/server/cherrypy/root.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_cherrypy_server.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tools/services/aid.py
- aim/tools/services/cherrypy_server.py
- aim/tools/services/cli.py
- rpm/aci-integration-module.spec.in
- rpm/aim-http-server.service
- setup.cfg
- test-requirements.txt
A new process 'aim-http-server' is introduced to expose a simple REST
API that wraps AIM functionalities and stores the AIM model into
the programmed store.
New configuration options have been added:
[aim_server]
port=8080
socket_file=/var/lib/aim/server.sock
binding_ip=127.0.0.1
> HTTP REST server for AIM

- aim/agent/aid/universes/aci/converter.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/migration/alembic_migrations/versions/dabed1dabeda_master_epgs.py
- aim/db/models.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
- tox.ini
requires support for fvRsSecInherited in apicapi.
Closes noironetworks/support#484
> Add support for master EPGs

- aim/agent/aid/universes/aim_universe.py
There are some cases where contention between the AIM Monitored
Universe and a user happen during Tenant manipulation. In these
cases, the user might delete a monitored Tenant while the universe
was going to update it, thus ending up with a stale tenant even
though the first deletion actually succeeded. This happens because
the Monitored universe overwrites objects instead of updating them,
we should make sure that root objects call the manager "update"
function instead.
> Monitored universe should not create Root objects

- aim/agent/aid/universes/aci/converter.py
- aim/db/migration/alembic_migrations/versions/6d55c6f80f40_svi.py
- aim/tests/unit/agent/aid_universes/test_converter.py
Also dropped the foreign key constraints per the discussion with Ivar. This
will allow objects being created without the parents.
> Fix the router_id_loopback converter issue.

- aim/agent/aid/universes/aci/converters/service_graph.py
- aim/agent/aid/universes/aci/converters/utils.py
- aim/api/resource.py
- aim/api/service_graph.py
- aim/db/hashtree_db_listener.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/migration/alembic_migrations/versions/bca1ef645fe1_epg_sync_flag.py
- aim/db/migration/alembic_migrations/versions/bca1ef645fe1_epg_sync_flag_and_node_counter.py
- aim/db/model_base.py
- aim/db/models.py
- aim/db/service_graph_model.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tree_manager.py
> Sync Flag, Service Graph conversion fix, SG linear nodes order fix.

- aim/agent/aid/event_services/rpc.py
- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/converter.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/base_universe.py
- aim/common/hashtree/structured_tree.py
- aim/config.py
- aim/db/agent_model.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- Work around the ACI bugs that doesn't return VMMP root object
upon subscription. Fake it, so that AID can show the smiley face
again;
- Remove some debug logs that were flooding the loggin file.
> Code housekeeping

- aim/aim_lib/nat_strategy.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
The existing API for L3 Out configuration doesn't allow the
caller to specify the VMM or Physical Domains that should be
associated to the external EPG created for the L3 Out. The
EPG is then associated with all VMM domains. This commit
adds the ability to control VMM and Physical Domain asociation.
> Add VMM domain configuration to L3 out

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
In some setups we see objects suddenly becoming "monitored"
and completely wrong hashtrees. This is happening because in
certain situations we have 2 separate threads serving the same
tenant. When this happens, they get events in parallel and the
leaked tenant ends up stealing some events from the right one,
thus causing these inconsistencies.
> Fix multi thread tenant

- rpm/aci-integration-module.spec.in
Added post install actions for AIM services
> Added post install actions for AIM services

- debian/aim-aid.service
- rpm/aim-aid.service
Moved StartLimitIntervalSec from service to unit section
> Moved StartLimitIntervalSec from service to unit section

- aim/common/hashring.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_hash_ring.py
> By default, set hashring replicas to 1.

- aim/tools/cli/commands/manager.py
The laod-mappings command was changed in commit
978d5b03181833d4bd20efa41b7e2acc03bc3269, so that an entry
in the HostDomainMappingV2 was created for each domain found
in the AIM DB. The correct behavior should be to create an
entry for each domain created from the configuration file.
> Fix load-mappings comand

- aim/agent/aid/universes/aci/converters/service_graph.py
- aim/api/service_graph.py
- aim/api/types.py
- aim/db/migration/alembic_migrations/versions/1b58ffa871bb_add_host_column.py
- aim/db/migration/data_migration/add_host_column.py
- aim/db/models.py
- aim/db/service_graph_model.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/test_migration.py
This makes it easier to query for entities deployed in a specific
host.
> Add host column to EPGs and Concrete devices

- aim/agent/aid/universes/aci/tenant.py
This will save some ACI errors in certain situations
> Delete before create on ACI

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
Make it easy to swap acitoolkit threads to serve.
> Fix aci universe thread monitor

- aim/aim_manager.py
This will make sure that an ActionLog is created and
the hashtree updated properly.
> Make sure status update is forced on DB

- aim/agent/aid/event_services/rpc.py
- aim/aim_store.py
- aim/db/api.py
- aim/tests/base.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_cherrypy_server.py
- aim/tests/unit/test_hashtree_db_listener.py
- aim/tests/unit/test_migration.py
> Make sure re-initializing commit hooks is safe for store

- debian/aim-aid.service
- debian/aim-http-server.service
- debian/install
- rpm/aim-aid.service
1. Removed extra comma in Wants= directive
2. Added debian/aim-aid.service for debian packages
> Fixed systemd services files

- aim/tests/unit/tools/cli/test_manager.py
- aim/tools/cli/commands/manager.py
Which will update all the objects in error state for easier
recovery procedure.
> Introduce sync state recover command

- aim/db/migration/alembic_migrations/versions/444afa12da26_modify_aim_id_column.py
not null needs to be explicitly set
> Fix aim_id column alteration for mysql

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/agent/aid/universes/constants.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/resource.py
- aim/common/utils.py
- aim/config.py
- aim/db/hashtree_db_listener.py
- aim/exceptions.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aim_db_universe.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/test_aim_manager.py
- aim/tree_manager.py
> Sync recovery rebase

- aim/aim_lib/nat_strategy.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
This is only needed for NoNat at this moment.
> Define new APIs for MD to add/remove a l3out to the BD

- aim/agent/aid/universes/aci/tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
If a parent is also getting deleted then we don't have to send
those children delete requests to APIC because APIC can just
remove the whole tree based on the parent's DN.
> Avoid sending the delete requests of children to APIC

- aim/aim_store.py
This patch relaxes serializtion of changes to
SecurityGroupRuleRemoteIp table entries by removing updates of the
epoch in SecurityGroupRule entries when there are no changes to the
other rows of the SecurityGroupRule itself. A corresponding fix is
needed for the processing of the associated ActionLog entries, in order
to ensure that correctness is maintained in the face of concurrent
updates to the same SecurityGroupRule entry.
> Fix StaleDataError exceptions

- aim/db/models.py
For the case where a SecurityGroupRule has its remote_ips member
updated, the list of SecurityGroupRuleRemoteIp objects is reconstructed
from scratch on each update call. This patch introduces a performance
improvement that uses sets to determine additions and deletions, and
then modifies the existing list of SecurityGroupRuleRemoteIp objects
accordingly.
> Fix SecurityGroupRule scalability

- aim/agent/aid/universes/aci/aci_universe.py
1. Have to reset all the tenants once a rotation happens. This
will make those tenants re-subscribe again with the new APIC
connection.
2. No need to subscribe again for each tenant when there is an
APIC event available. This is problematic because if this
subcribe fails, each tenant will try to re-establish a new APIC
connection but then other tenants are not getting notified to
re-subscribe. There is only one APIC connection for all the tenants
so this should not be handled by each tenant.
> Make sure the APIC rotation will work

- aim/aim_store.py
- aim/tests/unit/test_aim_manager.py
This reverts commit a422bc6b24c4686625e8dfa45b47d0b09bd63c8f.
> Revert "Fix query_statuses to return empty list if no aim res provided"

- aim/common/hashring.py
- aim/tests/unit/test_hash_ring.py
Added UTs to cover that. Also enhanced the UTs a bit.
> Fixed a bug in the hashring remove_nodes() API

- aim/tools/cli/commands/manager.py
- aim/tools/cli/groups/aimcli.py
Added json out support. Currently used by aimctl manager command
Use as: 'aimctl -f json manager <rest of command>'
> Added support for -f json for aimctl manager cmd

- aim/agent/aid/service.py
Detect and resolve any deadlock condition in the main aim-aid
deamon loop.
> Fix deadlocks

- rpm/aci-integration-module.spec.in
Added python-semantic_version package as a dependency
> Add python-semantic_version dependency

- aim/tests/unit/tools/cli/test_manager.py
- aim/tools/cli/commands/infra.py
Add AIM CLI commands for finding and deleting tags in ACI.
> Tag handling commands

- aim/tests/unit/test_aim_manager.py
This will take care the complilated data like a list/dictionary
or even nested objects like a list of dictionaries.
> Use the is_equal() from utils.py to compare the objects.

- aim/db/hashtree_db_listener.py
- aim/tests/unit/test_hashtree_db_listener.py
Inside this API, it will call _push_changes_to_trees() which will
then call _delete_logs() for each tenant respectively. What we
found from customer debug logs shows that if aim-aid got killed
by the watchdog while in the middle of _push_changes_to_trees()
due to some spike of action logs, those deleted action logs will
show up again even in the next restart because they were rolled
back by the outmost transaction. By scoping it with each tenant,
the backlog of action logs should reduce after each restart, which
will allow aim-aid to gradually recover itself instead of keep
getting killed by the watchdog. This change could potentially
increase the number of 'serve' and 'reconcile' events posted to
the event queue consumed by aim-aid. However since there is already
a sqash mechanism in …
> Scope the catch_up_with_action_logs() by each tenant

- aim/agent/aid/universes/aci/converter.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/4caed435b0cd_add_netflow.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/models.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/tools/cli/test_manager.py
Added code to enable netflow on openstack setups
> Code to enable netflow on Openstack setups

- rpm/aci-integration-module.spec.in
- rpm/build-rpm.sh
Update package names to support packages for both RHEL7 and RHEL8.
> Support python2 packages for RHEL7/8

- aim/db/models.py
- aim/tests/unit/test_aim_manager.py
This is a fix for the scaling issue on in #309.
A new testcase `test_static_path_scale ` was added to test the scaling of static paths. 
In the testcase we add 199 static paths and then in a second step add one new static path, remove one existing and update another one. 
The fix for this issue is to update the static paths in place instead of re-creating them every time even when only one new static path is added.
Here are some numbers:
Runtime of the `test_static_path_scale` test:  
- Fixed version:      2.2s
- Original version: 10.9s 
This is also visible in the number of SELECT statements on the aim_endpoint_groups table:
- Fixed version:         7 
- Original version: 206
> Fix for scaling issue of static paths

- aim/agent/aid/universes/k8s/k8s_watcher.py
- aim/k8s/api_v1.py
- aim/server/cherrypy/root.py
- aim/tests/unit/test_cherrypy_server.py
- aim/tools/cli/debug/hashtree.py
Calls to iteritems should be replaced by calls to items in order
to support py2/py3 compatibility.
> Fix calls to iteritems

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
The current AIM architecture allows resources to be created
in AIM, even if a resource they depend on doesn't yet exist
(e.g. EndpointGroup referencing a BridgeDomain). When AID sees
resources in AIM that it needs to reconcile with ACI, it doesn't
take into account dependent objects. This can result in temporary
or long-term faults, which can be at the least confusing, or at
the worst result in unintended configuration (e.g. if a source or
destination SPAN group is referenced by a InfraAccBundleGroup
resource, and those resources don't yet exist in APIC, APIC may
choose to resolve them to a default SPAN source and/or destination
group instead, leading to a broken ERSPAN policy). In order to avoid
these issues, a method is introduced that delays POSTing of a resource
until its dependencies …
> Delay pushing dependent resources

- aim/api/resource.py
Change-Id: I1a7ccafc5587fbd812d2e773d322d9d79a97fe66
> Correct typo in policy_enforcement_pref EPG resource values

- aim/agent/aid/universes/aci/converter.py
- aim/aim_manager.py
- aim/aim_store.py
- aim/api/resource.py
- aim/db/migration/alembic_migrations/versions/61db5ac02ffa_add_oob_contract.py
- aim/db/migration/alembic_migrations/versions/HEAD
- aim/db/models.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_converter.py
- aim/tests/unit/test_aim_manager.py
- aim/tests/unit/tools/cli/test_manager.py
Adding Out of Band Contract MO
> Add support for out of band contracts

- requirements.txt
Pin jsonschema for python2.7 builds.
> Fix python2.7 builds

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/common/hashtree/structured_tree.py
- aim/tests/unit/test_structured_hash_tree.py
This reverts commit 4fb4cabf8a7e0cbb9546b892d4a3867a19fa0d04.
> Revert "Don't delete the tenant prematurely"

- aim/agent/aid/universes/aci/aci_universe.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
The apicapi client requires logging in to APIC under certain
conditions, such as continued authorization failures. This patch
adds a class that attempts to reauthorize/login with APIC if the
auth token becomes invalidated. The authorization class tries to
refresh the login within half of the login timeout period that
was returned by APIC in the authorization response/token.
> Add APIC login class

- aim/agent/aid/universes/aci/aci_universe.py
Fix incorrect kwargs parameter name.
> Fix websocket refreshes

- aim/agent/aid/universes/aci/tenant.py
- aim/agent/aid/universes/aim_universe.py
- aim/agent/aid/universes/base_universe.py
- aim/common/hashtree/structured_tree.py
- aim/tests/unit/test_structured_hash_tree.py
This reverts commit e9cf65874c70c720d2dda5f3c822bbf79c2e1c8f.
> Revert "Revert "Don't delete the tenant prematurely""

- aim/aim_lib/nat_strategy.py
Commit 8a8c6911a073d20d25858e39e6ab66ce759a5ea9 made the contract
references under the external network top level AIM resources.
This patch ensures that those resources get removed when the
external network is removed.
> Remove provided/consumed contracts

- aim/aim_lib/nat_strategy.py
- aim/db/models.py
- aim/tests/unit/agent/test_agent.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
- aim/tests/unit/test_aim_manager.py
This reverts commit 9076bd8738e27052e75ec53052e509c54c4b91ea.
> Revert "Fix use of ExternalNetwork contracts"

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/test_agent.py
Change-Id: Ia017bfdae7397a89b1295877d59188532700c20a
> Apic Client Fix

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/tests/base.py
- aim/tests/unit/agent/aid_universes/test_aci_tenant.py
- aim/tests/unit/agent/aid_universes/test_aci_universe.py
- aim/tests/unit/agent/test_agent.py
This reverts commit 3fe0a7e4284c5b07b9131758b4abc6080365e3f8.
> Revert "Apic Client Fix"

- aim/agent/aid/universes/aci/aci_universe.py
Fix the code that leads to the log error:
There is no such apic_assign_obj exist
Change-Id: I84550c589d6645248e5c97fd1c0e27c8768e8c0d
> Fix Log Error

- aim/aim_lib/nat_strategy.py
- aim/tests/unit/aim_lib/test_nat_strategy.py
Support for alternative naming scheme for epgs.
> L3Outside Multi External Network Support

- aim/aim_lib/nat_strategy.py
Fixes the deletion of subnets while using the multi_ext_nets extension.
Now, only the subnets associated with the given network are deleted.
> L3Out Multi Ext Networks Subnet Fix

- aim/api/resource.py
Add scope constants for 'shared' and 'public,shared'
> Add scope constants

- aim/aim_lib/nat_strategy.py
Fixed issue where some methods didn't get passed the new epg_name.
This caused them to assume the epg was using the default name scheme,
which is incorrect when using the multi ext network extension.
> Fixed Multi Ext Network Resource Creation

- test-requirements.txt
Fix the test-requirements.txt for updating the correct version of voluptuous library for tox tests
> fix tox env for voluptuous lib

- aim/agent/aid/universes/aci/aci_universe.py
- aim/agent/aid/universes/aci/tenant.py
- aim/api/resource.py
- aim/common/hashring.py
- aim/common/utils.py
- aim/db/migration/data_migration/status_add_dn.py
Fixing the static analysis vulnerabilities that were reported through bandit runs/ marking the false positives.
> Fixing static analysis vulnerabilities for aim

- rpm/my_setup_dev.sh
- rpm/pipeline-rpm-script
- rpm/sign-rpm.sh
- added capability to sign aci-integration-module rpm
> updated pipeline script

- rpm/pipeline-rpm-script
Added escape \ to ARTIFACT_TOKEN variable to avoid  insecure interpolation of sensitive variables
> Update artifactory step in pipeline script

- aim/db/migration/data_migration/static_paths_v2.py
Fix bug where the static path resource comes as non monitored when it should be monitored.
> Fix bug in static paths fix

- aim/api/resource.py
- aim/api/types.py
(cherry picked from commit c563c7ec5b107045235f3c9a338a0c443877dbd7)
> ESP protocol in SG
